<?php

namespace App\Services\Telegram;

use App\Enums\Language;
use Closure;
use Illuminate\Support\Facades\Lang;
use InvalidArgumentException;

/**
 * The one way to produce a bot message (PRD §19): a fixed template from lang/{id,en}/bot.php with
 * 2–3 variants, picked at random. Bot text is never generated by AI (CLAUDE.md rule 8).
 *
 * Keys are `<area>.<situation>` (e.g. `worklog.ack`). Placeholders use Laravel's `:name` style.
 */
final class BotMessages
{
    /** @var Closure(int): int */
    private readonly Closure $picker;

    /**
     * @param  (Closure(int): int)|null  $picker  returns an index in [0, count); tests inject a fixed one
     */
    public function __construct(?Closure $picker = null)
    {
        $this->picker = $picker ?? static fn (int $count): int => random_int(0, $count - 1);
    }

    /**
     * @param  array<string, scalar>  $replace
     */
    public function get(string $key, Language|string $language, array $replace = []): string
    {
        $variants = $this->variants($key, $language);
        $template = $variants[($this->picker)(count($variants))];

        // Longest names first so :count_total is not clobbered by :count.
        uksort($replace, fn (string $a, string $b): int => strlen($b) <=> strlen($a));

        foreach ($replace as $name => $value) {
            $template = str_replace(':'.$name, (string) $value, $template);
        }

        return $template;
    }

    /**
     * @return non-empty-list<string>
     */
    public function variants(string $key, Language|string $language): array
    {
        $locale = $language instanceof Language ? $language->value : $language;
        $variants = Lang::get('bot.'.$key, [], $locale, false);

        if (! is_array($variants) || $variants === [] || ! array_is_list($variants)) {
            throw new InvalidArgumentException("Unknown bot message key [{$key}] for locale [{$locale}].");
        }

        /** @var non-empty-list<string> $variants */
        return $variants;
    }
}
